# Generated by Django 6.0.3 on 2026-03-08 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('quartos', models.IntegerField(blank=True, default=0, null=True)),
                ('banheiros', models.PositiveIntegerField(default=0)),
                ('vagas_garagem', models.PositiveIntegerField(default=0)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('tem_varanda', models.BooleanField(default=False)),
                ('tem_terraco', models.BooleanField(default=False)),
                ('finalidade', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], default='venda', max_length=20)),
                ('categoria', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Ponto Comercial', 'Ponto Comercial'), ('Sitio', 'Sítio'), ('Fazenda', 'Fazenda'), ('Condominio Fechado', 'Condomínio Fechado')], default='Casa', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='anuncios/')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('creci', models.CharField(blank=True, max_length=20, null=True)),
                ('plano', models.CharField(choices=[('basico', 'Básico (Grátis)'), ('pro', 'Pro (R$ 5,99)'), ('premium', 'Premium (R$ 7,99)')], default='basico', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
