# Generated by Django 6.0.3 on 2026-03-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0002_corretor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='banheiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='vagas_garagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnuncioImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='corretores.anuncio')),
            ],
        ),
    ]
