# Generated by Django 6.0.3 on 2026-03-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0003_alter_anuncio_banheiros_alter_anuncio_vagas_garagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='uf',
            field=models.CharField(default='PB', max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
    ]
