# Generated by Django 6.0.3 on 2026-03-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0004_anuncio_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='acessos',
            field=models.IntegerField(default=0),
        ),
    ]
